// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: api/internal/modules/agent/interfaces/grpc/proto/agent.proto

package grpcpb

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ControlMessage struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MessageId      string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,2,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"` // Dedup execution
	// Types that are valid to be assigned to Payload:
	//
	//	*ControlMessage_ExecuteTask
	//	*ControlMessage_TriggerSkill
	//	*ControlMessage_CancelExecution
	//	*ControlMessage_ServiceAction
	//	*ControlMessage_ListServices
	Payload       isControlMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ControlMessage) Reset() {
	*x = ControlMessage{}
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ControlMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ControlMessage) ProtoMessage() {}

func (x *ControlMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ControlMessage.ProtoReflect.Descriptor instead.
func (*ControlMessage) Descriptor() ([]byte, []int) {
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP(), []int{0}
}

func (x *ControlMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ControlMessage) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *ControlMessage) GetPayload() isControlMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ControlMessage) GetExecuteTask() *ExecuteTask {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ExecuteTask); ok {
			return x.ExecuteTask
		}
	}
	return nil
}

func (x *ControlMessage) GetTriggerSkill() *TriggerSkill {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_TriggerSkill); ok {
			return x.TriggerSkill
		}
	}
	return nil
}

func (x *ControlMessage) GetCancelExecution() *CancelExecution {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_CancelExecution); ok {
			return x.CancelExecution
		}
	}
	return nil
}

func (x *ControlMessage) GetServiceAction() *ServiceAction {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ServiceAction); ok {
			return x.ServiceAction
		}
	}
	return nil
}

func (x *ControlMessage) GetListServices() *ListServices {
	if x != nil {
		if x, ok := x.Payload.(*ControlMessage_ListServices); ok {
			return x.ListServices
		}
	}
	return nil
}

type isControlMessage_Payload interface {
	isControlMessage_Payload()
}

type ControlMessage_ExecuteTask struct {
	ExecuteTask *ExecuteTask `protobuf:"bytes,10,opt,name=execute_task,json=executeTask,proto3,oneof"`
}

type ControlMessage_TriggerSkill struct {
	TriggerSkill *TriggerSkill `protobuf:"bytes,11,opt,name=trigger_skill,json=triggerSkill,proto3,oneof"`
}

type ControlMessage_CancelExecution struct {
	CancelExecution *CancelExecution `protobuf:"bytes,12,opt,name=cancel_execution,json=cancelExecution,proto3,oneof"`
}

type ControlMessage_ServiceAction struct {
	ServiceAction *ServiceAction `protobuf:"bytes,13,opt,name=service_action,json=serviceAction,proto3,oneof"`
}

type ControlMessage_ListServices struct {
	ListServices *ListServices `protobuf:"bytes,14,opt,name=list_services,json=listServices,proto3,oneof"`
}

func (*ControlMessage_ExecuteTask) isControlMessage_Payload() {}

func (*ControlMessage_TriggerSkill) isControlMessage_Payload() {}

func (*ControlMessage_CancelExecution) isControlMessage_Payload() {}

func (*ControlMessage_ServiceAction) isControlMessage_Payload() {}

func (*ControlMessage_ListServices) isControlMessage_Payload() {}

// ExecuteTask instructs the agent to run a raw shell command or binary.
type ExecuteTask struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Cmd           string                 `protobuf:"bytes,2,opt,name=cmd,proto3" json:"cmd,omitempty"`
	TimeoutS      int32                  `protobuf:"varint,3,opt,name=timeout_s,json=timeoutS,proto3" json:"timeout_s,omitempty"`
	Env           map[string]string      `protobuf:"bytes,4,rep,name=env,proto3" json:"env,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteTask) Reset() {
	*x = ExecuteTask{}
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteTask) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteTask) ProtoMessage() {}

func (x *ExecuteTask) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteTask.ProtoReflect.Descriptor instead.
func (*ExecuteTask) Descriptor() ([]byte, []int) {
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ExecuteTask) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *ExecuteTask) GetCmd() string {
	if x != nil {
		return x.Cmd
	}
	return ""
}

func (x *ExecuteTask) GetTimeoutS() int32 {
	if x != nil {
		return x.TimeoutS
	}
	return 0
}

func (x *ExecuteTask) GetEnv() map[string]string {
	if x != nil {
		return x.Env
	}
	return nil
}

// TriggerSkill tells the agent to execute a pre-defined Antigravity Skill locally.
type TriggerSkill struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SkillName     string                 `protobuf:"bytes,2,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`                                                      // E.g., "@security-auditor"
	Context       map[string]string      `protobuf:"bytes,3,rep,name=context,proto3" json:"context,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"` // Data payload containing files, logs, etc.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TriggerSkill) Reset() {
	*x = TriggerSkill{}
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TriggerSkill) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TriggerSkill) ProtoMessage() {}

func (x *TriggerSkill) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TriggerSkill.ProtoReflect.Descriptor instead.
func (*TriggerSkill) Descriptor() ([]byte, []int) {
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP(), []int{2}
}

func (x *TriggerSkill) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TriggerSkill) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *TriggerSkill) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type CancelExecution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TargetTaskId  string                 `protobuf:"bytes,1,opt,name=target_task_id,json=targetTaskId,proto3" json:"target_task_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelExecution) Reset() {
	*x = CancelExecution{}
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelExecution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelExecution) ProtoMessage() {}

func (x *CancelExecution) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelExecution.ProtoReflect.Descriptor instead.
func (*CancelExecution) Descriptor() ([]byte, []int) {
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP(), []int{3}
}

func (x *CancelExecution) GetTargetTaskId() string {
	if x != nil {
		return x.TargetTaskId
	}
	return ""
}

// ServiceAction instructs the agent to perform an action on a system service.
type ServiceAction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"` // start, stop, restart, enable, disable
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceAction) Reset() {
	*x = ServiceAction{}
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceAction) ProtoMessage() {}

func (x *ServiceAction) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceAction.ProtoReflect.Descriptor instead.
func (*ServiceAction) Descriptor() ([]byte, []int) {
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP(), []int{4}
}

func (x *ServiceAction) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ServiceAction) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// ListServices requests the agent to return a list of system services.
type ListServices struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	FilterPattern string                 `protobuf:"bytes,1,opt,name=filter_pattern,json=filterPattern,proto3" json:"filter_pattern,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListServices) Reset() {
	*x = ListServices{}
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListServices) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListServices) ProtoMessage() {}

func (x *ListServices) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListServices.ProtoReflect.Descriptor instead.
func (*ListServices) Descriptor() ([]byte, []int) {
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP(), []int{5}
}

func (x *ListServices) GetFilterPattern() string {
	if x != nil {
		return x.FilterPattern
	}
	return ""
}

type AgentEvent struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	ServerId    string                 `protobuf:"bytes,1,opt,name=server_id,json=serverId,proto3" json:"server_id,omitempty"`
	SessionId   string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"` // Unique connection session string
	TimestampMs int64                  `protobuf:"varint,3,opt,name=timestamp_ms,json=timestampMs,proto3" json:"timestamp_ms,omitempty"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentEvent_Register
	//	*AgentEvent_Heartbeat
	//	*AgentEvent_TaskOutput
	//	*AgentEvent_SkillResult
	//	*AgentEvent_ServiceList
	Payload       isAgentEvent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentEvent) Reset() {
	*x = AgentEvent{}
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentEvent) ProtoMessage() {}

func (x *AgentEvent) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentEvent.ProtoReflect.Descriptor instead.
func (*AgentEvent) Descriptor() ([]byte, []int) {
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP(), []int{6}
}

func (x *AgentEvent) GetServerId() string {
	if x != nil {
		return x.ServerId
	}
	return ""
}

func (x *AgentEvent) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *AgentEvent) GetTimestampMs() int64 {
	if x != nil {
		return x.TimestampMs
	}
	return 0
}

func (x *AgentEvent) GetPayload() isAgentEvent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentEvent) GetRegister() *RegisterRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Register); ok {
			return x.Register
		}
	}
	return nil
}

func (x *AgentEvent) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentEvent) GetTaskOutput() *TaskOutput {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_TaskOutput); ok {
			return x.TaskOutput
		}
	}
	return nil
}

func (x *AgentEvent) GetSkillResult() *SkillExecutionResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_SkillResult); ok {
			return x.SkillResult
		}
	}
	return nil
}

func (x *AgentEvent) GetServiceList() *ServiceListResponse {
	if x != nil {
		if x, ok := x.Payload.(*AgentEvent_ServiceList); ok {
			return x.ServiceList
		}
	}
	return nil
}

type isAgentEvent_Payload interface {
	isAgentEvent_Payload()
}

type AgentEvent_Register struct {
	Register *RegisterRequest `protobuf:"bytes,10,opt,name=register,proto3,oneof"`
}

type AgentEvent_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,11,opt,name=heartbeat,proto3,oneof"`
}

type AgentEvent_TaskOutput struct {
	TaskOutput *TaskOutput `protobuf:"bytes,12,opt,name=task_output,json=taskOutput,proto3,oneof"`
}

type AgentEvent_SkillResult struct {
	SkillResult *SkillExecutionResult `protobuf:"bytes,13,opt,name=skill_result,json=skillResult,proto3,oneof"`
}

type AgentEvent_ServiceList struct {
	ServiceList *ServiceListResponse `protobuf:"bytes,14,opt,name=service_list,json=serviceList,proto3,oneof"`
}

func (*AgentEvent_Register) isAgentEvent_Payload() {}

func (*AgentEvent_Heartbeat) isAgentEvent_Payload() {}

func (*AgentEvent_TaskOutput) isAgentEvent_Payload() {}

func (*AgentEvent_SkillResult) isAgentEvent_Payload() {}

func (*AgentEvent_ServiceList) isAgentEvent_Payload() {}

// ServiceListResponse is the response to a ListServices command.
type ServiceListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RequestId     string                 `protobuf:"bytes,1,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Services      []*ServiceEntry        `protobuf:"bytes,2,rep,name=services,proto3" json:"services,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceListResponse) Reset() {
	*x = ServiceListResponse{}
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceListResponse) ProtoMessage() {}

func (x *ServiceListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceListResponse.ProtoReflect.Descriptor instead.
func (*ServiceListResponse) Descriptor() ([]byte, []int) {
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP(), []int{7}
}

func (x *ServiceListResponse) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *ServiceListResponse) GetServices() []*ServiceEntry {
	if x != nil {
		return x.Services
	}
	return nil
}

type ServiceEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Status        string                 `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`   // active, inactive, failed
	Startup       string                 `protobuf:"bytes,4,opt,name=startup,proto3" json:"startup,omitempty"` // enabled, disabled
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceEntry) Reset() {
	*x = ServiceEntry{}
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceEntry) ProtoMessage() {}

func (x *ServiceEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceEntry.ProtoReflect.Descriptor instead.
func (*ServiceEntry) Descriptor() ([]byte, []int) {
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP(), []int{8}
}

func (x *ServiceEntry) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ServiceEntry) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *ServiceEntry) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ServiceEntry) GetStartup() string {
	if x != nil {
		return x.Startup
	}
	return ""
}

type RegisterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AgentVersion  string                 `protobuf:"bytes,1,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	Os            string                 `protobuf:"bytes,2,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,3,opt,name=arch,proto3" json:"arch,omitempty"`
	Capabilities  []string               `protobuf:"bytes,4,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP(), []int{9}
}

func (x *RegisterRequest) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *RegisterRequest) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *RegisterRequest) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *RegisterRequest) GetCapabilities() []string {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

type Heartbeat struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CpuPercent    float32                `protobuf:"fixed32,1,opt,name=cpu_percent,json=cpuPercent,proto3" json:"cpu_percent,omitempty"`
	MemPercent    float32                `protobuf:"fixed32,2,opt,name=mem_percent,json=memPercent,proto3" json:"mem_percent,omitempty"`
	UptimeSeconds int64                  `protobuf:"varint,3,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
	TimestampMs   int64
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP(), []int{10}
}

func (x *Heartbeat) GetCpuPercent() float32 {
	if x != nil {
		return x.CpuPercent
	}
	return 0
}

func (x *Heartbeat) GetMemPercent() float32 {
	if x != nil {
		return x.MemPercent
	}
	return 0
}

func (x *Heartbeat) GetUptimeSeconds() int64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

// Streamed incrementally as standard out/err arrives.
type TaskOutput struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	Data          []byte                 `protobuf:"bytes,2,opt,name=data,proto3" json:"data,omitempty"`
	IsStderr      bool                   `protobuf:"varint,3,opt,name=is_stderr,json=isStderr,proto3" json:"is_stderr,omitempty"`
	Seq           int64                  `protobuf:"varint,4,opt,name=seq,proto3" json:"seq,omitempty"` // Chunk sequence number to maintain ordering
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TaskOutput) Reset() {
	*x = TaskOutput{}
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskOutput) ProtoMessage() {}

func (x *TaskOutput) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskOutput.ProtoReflect.Descriptor instead.
func (*TaskOutput) Descriptor() ([]byte, []int) {
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP(), []int{11}
}

func (x *TaskOutput) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskOutput) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TaskOutput) GetIsStderr() bool {
	if x != nil {
		return x.IsStderr
	}
	return false
}

func (x *TaskOutput) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

// Sent when a complex Skill or Task finishes executing.
type SkillExecutionResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskId        string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	SkillName     string                 `protobuf:"bytes,2,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	ExitCode      int32                  `protobuf:"varint,3,opt,name=exit_code,json=exitCode,proto3" json:"exit_code,omitempty"`
	FinalOutput   string                 `protobuf:"bytes,4,opt,name=final_output,json=finalOutput,proto3" json:"final_output,omitempty"` // The aggregated intelligence/result
	ErrorReason   string                 `protobuf:"bytes,5,opt,name=error_reason,json=errorReason,proto3" json:"error_reason,omitempty"` // Populated if failure occurred
	DurationMs    int64                  `protobuf:"varint,6,opt,name=duration_ms,json=durationMs,proto3" json:"duration_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillExecutionResult) Reset() {
	*x = SkillExecutionResult{}
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillExecutionResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillExecutionResult) ProtoMessage() {}

func (x *SkillExecutionResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillExecutionResult.ProtoReflect.Descriptor instead.
func (*SkillExecutionResult) Descriptor() ([]byte, []int) {
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP(), []int{12}
}

func (x *SkillExecutionResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *SkillExecutionResult) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *SkillExecutionResult) GetExitCode() int32 {
	if x != nil {
		return x.ExitCode
	}
	return 0
}

func (x *SkillExecutionResult) GetFinalOutput() string {
	if x != nil {
		return x.FinalOutput
	}
	return ""
}

func (x *SkillExecutionResult) GetErrorReason() string {
	if x != nil {
		return x.ErrorReason
	}
	return ""
}

func (x *SkillExecutionResult) GetDurationMs() int64 {
	if x != nil {
		return x.DurationMs
	}
	return 0
}

var File_api_internal_modules_agent_interfaces_grpc_proto_agent_proto protoreflect.FileDescriptor

const file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDesc = "" +
	"\n" +
	"<api/internal/modules/agent/interfaces/grpc/proto/agent.proto\x12\bagent.v1\"\xa7\x03\n" +
	"\x0eControlMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12'\n" +
	"\x0fidempotency_key\x18\x02 \x01(\tR\x0eidempotencyKey\x12:\n" +
	"\fexecute_task\x18\n" +
	" \x01(\v2\x15.agent.v1.ExecuteTaskH\x00R\vexecuteTask\x12=\n" +
	"\rtrigger_skill\x18\v \x01(\v2\x16.agent.v1.TriggerSkillH\x00R\ftriggerSkill\x12F\n" +
	"\x10cancel_execution\x18\f \x01(\v2\x19.agent.v1.CancelExecutionH\x00R\x0fcancelExecution\x12@\n" +
	"\x0eservice_action\x18\r \x01(\v2\x17.agent.v1.ServiceActionH\x00R\rserviceAction\x12=\n" +
	"\rlist_services\x18\x0e \x01(\v2\x16.agent.v1.ListServicesH\x00R\flistServicesB\t\n" +
	"\apayload\"\xbf\x01\n" +
	"\vExecuteTask\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x10\n" +
	"\x03cmd\x18\x02 \x01(\tR\x03cmd\x12\x1b\n" +
	"\ttimeout_s\x18\x03 \x01(\x05R\btimeoutS\x120\n" +
	"\x03env\x18\x04 \x03(\v2\x1e.agent.v1.ExecuteTask.EnvEntryR\x03env\x1a6\n" +
	"\bEnvEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xc1\x01\n" +
	"\fTriggerSkill\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x02 \x01(\tR\tskillName\x12=\n" +
	"\acontext\x18\x03 \x03(\v2#.agent.v1.TriggerSkill.ContextEntryR\acontext\x1a:\n" +
	"\fContextEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"7\n" +
	"\x0fCancelExecution\x12$\n" +
	"\x0etarget_task_id\x18\x01 \x01(\tR\ftargetTaskId\"J\n" +
	"\rServiceAction\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"5\n" +
	"\fListServices\x12%\n" +
	"\x0efilter_pattern\x18\x01 \x01(\tR\rfilterPattern\"\xa6\x03\n" +
	"\n" +
	"AgentEvent\x12\x1b\n" +
	"\tserver_id\x18\x01 \x01(\tR\bserverId\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12!\n" +
	"\ftimestamp_ms\x18\x03 \x01(\x03R\vtimestampMs\x127\n" +
	"\bregister\x18\n" +
	" \x01(\v2\x19.agent.v1.RegisterRequestH\x00R\bregister\x123\n" +
	"\theartbeat\x18\v \x01(\v2\x13.agent.v1.HeartbeatH\x00R\theartbeat\x127\n" +
	"\vtask_output\x18\f \x01(\v2\x14.agent.v1.TaskOutputH\x00R\n" +
	"taskOutput\x12C\n" +
	"\fskill_result\x18\r \x01(\v2\x1e.agent.v1.SkillExecutionResultH\x00R\vskillResult\x12B\n" +
	"\fservice_list\x18\x0e \x01(\v2\x1d.agent.v1.ServiceListResponseH\x00R\vserviceListB\t\n" +
	"\apayload\"h\n" +
	"\x13ServiceListResponse\x12\x1d\n" +
	"\n" +
	"request_id\x18\x01 \x01(\tR\trequestId\x122\n" +
	"\bservices\x18\x02 \x03(\v2\x16.agent.v1.ServiceEntryR\bservices\"v\n" +
	"\fServiceEntry\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x16\n" +
	"\x06status\x18\x03 \x01(\tR\x06status\x12\x18\n" +
	"\astartup\x18\x04 \x01(\tR\astartup\"~\n" +
	"\x0fRegisterRequest\x12#\n" +
	"\ragent_version\x18\x01 \x01(\tR\fagentVersion\x12\x0e\n" +
	"\x02os\x18\x02 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x03 \x01(\tR\x04arch\x12\"\n" +
	"\fcapabilities\x18\x04 \x03(\tR\fcapabilities\"t\n" +
	"\tHeartbeat\x12\x1f\n" +
	"\vcpu_percent\x18\x01 \x01(\x02R\n" +
	"cpuPercent\x12\x1f\n" +
	"\vmem_percent\x18\x02 \x01(\x02R\n" +
	"memPercent\x12%\n" +
	"\x0euptime_seconds\x18\x03 \x01(\x03R\ruptimeSeconds\"h\n" +
	"\n" +
	"TaskOutput\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04data\x18\x02 \x01(\fR\x04data\x12\x1b\n" +
	"\tis_stderr\x18\x03 \x01(\bR\bisStderr\x12\x10\n" +
	"\x03seq\x18\x04 \x01(\x03R\x03seq\"\xd2\x01\n" +
	"\x14SkillExecutionResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x02 \x01(\tR\tskillName\x12\x1b\n" +
	"\texit_code\x18\x03 \x01(\x05R\bexitCode\x12!\n" +
	"\ffinal_output\x18\x04 \x01(\tR\vfinalOutput\x12!\n" +
	"\ferror_reason\x18\x05 \x01(\tR\verrorReason\x12\x1f\n" +
	"\vduration_ms\x18\x06 \x01(\x03R\n" +
	"durationMs2U\n" +
	"\fAgentService\x12E\n" +
	"\rConnectStream\x12\x14.agent.v1.AgentEvent\x1a\x18.agent.v1.ControlMessage\"\x00(\x010\x01B9Z7einfra/api/internal/modules/agent/infrastructure/grpcpbb\x06proto3"

var (
	file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescOnce sync.Once
	file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescData []byte
)

func file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescGZIP() []byte {
	file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescOnce.Do(func() {
		file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDesc), len(file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDesc)))
	})
	return file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDescData
}

var file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_goTypes = []any{
	(*ControlMessage)(nil),       // 0: agent.v1.ControlMessage
	(*ExecuteTask)(nil),          // 1: agent.v1.ExecuteTask
	(*TriggerSkill)(nil),         // 2: agent.v1.TriggerSkill
	(*CancelExecution)(nil),      // 3: agent.v1.CancelExecution
	(*ServiceAction)(nil),        // 4: agent.v1.ServiceAction
	(*ListServices)(nil),         // 5: agent.v1.ListServices
	(*AgentEvent)(nil),           // 6: agent.v1.AgentEvent
	(*ServiceListResponse)(nil),  // 7: agent.v1.ServiceListResponse
	(*ServiceEntry)(nil),         // 8: agent.v1.ServiceEntry
	(*RegisterRequest)(nil),      // 9: agent.v1.RegisterRequest
	(*Heartbeat)(nil),            // 10: agent.v1.Heartbeat
	(*TaskOutput)(nil),           // 11: agent.v1.TaskOutput
	(*SkillExecutionResult)(nil), // 12: agent.v1.SkillExecutionResult
	nil,                          // 13: agent.v1.ExecuteTask.EnvEntry
	nil,                          // 14: agent.v1.TriggerSkill.ContextEntry
}
var file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_depIdxs = []int32{
	1,  // 0: agent.v1.ControlMessage.execute_task:type_name -> agent.v1.ExecuteTask
	2,  // 1: agent.v1.ControlMessage.trigger_skill:type_name -> agent.v1.TriggerSkill
	3,  // 2: agent.v1.ControlMessage.cancel_execution:type_name -> agent.v1.CancelExecution
	4,  // 3: agent.v1.ControlMessage.service_action:type_name -> agent.v1.ServiceAction
	5,  // 4: agent.v1.ControlMessage.list_services:type_name -> agent.v1.ListServices
	13, // 5: agent.v1.ExecuteTask.env:type_name -> agent.v1.ExecuteTask.EnvEntry
	14, // 6: agent.v1.TriggerSkill.context:type_name -> agent.v1.TriggerSkill.ContextEntry
	9,  // 7: agent.v1.AgentEvent.register:type_name -> agent.v1.RegisterRequest
	10, // 8: agent.v1.AgentEvent.heartbeat:type_name -> agent.v1.Heartbeat
	11, // 9: agent.v1.AgentEvent.task_output:type_name -> agent.v1.TaskOutput
	12, // 10: agent.v1.AgentEvent.skill_result:type_name -> agent.v1.SkillExecutionResult
	7,  // 11: agent.v1.AgentEvent.service_list:type_name -> agent.v1.ServiceListResponse
	8,  // 12: agent.v1.ServiceListResponse.services:type_name -> agent.v1.ServiceEntry
	6,  // 13: agent.v1.AgentService.ConnectStream:input_type -> agent.v1.AgentEvent
	0,  // 14: agent.v1.AgentService.ConnectStream:output_type -> agent.v1.ControlMessage
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_init() }
func file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_init() {
	if File_api_internal_modules_agent_interfaces_grpc_proto_agent_proto != nil {
		return
	}
	file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*ControlMessage_ExecuteTask)(nil),
		(*ControlMessage_TriggerSkill)(nil),
		(*ControlMessage_CancelExecution)(nil),
		(*ControlMessage_ServiceAction)(nil),
		(*ControlMessage_ListServices)(nil),
	}
	file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes[6].OneofWrappers = []any{
		(*AgentEvent_Register)(nil),
		(*AgentEvent_Heartbeat)(nil),
		(*AgentEvent_TaskOutput)(nil),
		(*AgentEvent_SkillResult)(nil),
		(*AgentEvent_ServiceList)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDesc), len(file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_goTypes,
		DependencyIndexes: file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_depIdxs,
		MessageInfos:      file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_msgTypes,
	}.Build()
	File_api_internal_modules_agent_interfaces_grpc_proto_agent_proto = out.File
	file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_goTypes = nil
	file_api_internal_modules_agent_interfaces_grpc_proto_agent_proto_depIdxs = nil
}
